/* ============================================= */
/* === PRODUCTS DATA (shared catalog) ========== */
/* ============================================= */

const PRODUCTS = {
    /* ===== TOPS & HOODIES ===== */
    'sunset-brick-hoodie': {
        id: 'sunset-brick-hoodie',
        name: 'Sunset Brick',
        tag: 'Hoodie',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 18000,
        image: 'images/45.png',
        backImage: 'images/46.png',
        completewear: 'images/Completewear/44.png',
        partner: 'sunset-signature-joggers',
        badge: 'New',
        description:
            'Heavyweight 320GSM cotton hoodie finished in sunset orange and anchored by the FakeSmile brick crest. Pre-shrunk, double-stitched, with metal-tipped drawstrings and a kangaroo pocket — engineered to outlast the drop.',
        details: {
            Material: '320GSM heavyweight cotton, brushed back',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'cloud-brick-hoodie': {
        id: 'cloud-brick-hoodie',
        name: 'Cloud Brick',
        tag: 'Hoodie',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 18000,
        image: 'images/49.png',
        backImage: 'images/50.png',
        completewear: 'images/Completewear/45.png',
        partner: 'cloud-signature-joggers',
        description:
            'Cloud-white 320GSM cotton hoodie carrying the FakeSmile brick crest in muted contrast. Premium-feel brushed inner, ribbed cuffs and a streetwear-ready relaxed fit.',
        details: {
            Material: '320GSM heavyweight cotton, brushed back',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'midnight-brick-hoodie': {
        id: 'midnight-brick-hoodie',
        name: 'Midnight Brick',
        tag: 'Hoodie',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 18000,
        image: 'images/53.png',
        backImage: 'images/54.png',
        completewear: 'images/Completewear/46.png',
        partner: 'midnight-signature-joggers',
        badge: 'Bestseller',
        description:
            'The signature midnight-black hoodie. Heavyweight cotton, FakeSmile brick crest, double-stitched cuffs and metal-tipped drawstrings — the most-pulled fit in the wardrobe.',
        details: {
            Material: '320GSM heavyweight cotton, brushed back',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'crimson-court-jersey': {
        id: 'crimson-court-jersey',
        name: 'Crimson Court',
        tag: 'Jersey',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 12500,
        image: 'images/63.png',
        backImage: 'images/64.png',
        completewear: 'images/Completewear/49.png',
        partner: 'crimson-court-shorts',
        description:
            'Court-ready performance jersey in crimson with white trim. Lightweight breathable mesh tricot and the "FAKE A SMILE" wordmark — engineered for motion.',
        details: {
            Material: 'Lightweight breathable polyester tricot',
            Fit: 'Athletic, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash, do not iron print',
            Origin: 'Crafted in Lagos',
        },
    },
    'onyx-gold-jersey': {
        id: 'onyx-gold-jersey',
        name: 'Onyx Gold',
        tag: 'Jersey',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 12500,
        image: 'images/78.png',
        backImage: 'images/79.png',
        completewear: 'images/Completewear/55.png',
        partner: 'onyx-gold-shorts',
        badge: 'Limited',
        description:
            'Black-on-gold jersey with embroidered FakeSmile crest. Lightweight tricot, breathable mesh side panels and signature ribbed collar — limited run.',
        details: {
            Material: 'Lightweight breathable polyester tricot',
            Fit: 'Athletic, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash, do not iron print',
            Origin: 'Crafted in Lagos',
        },
    },
    'twin-faces-tank': {
        id: 'twin-faces-tank',
        name: 'Twin Faces',
        tag: 'Tank',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 9500,
        image: 'images/92.png',
        backImage: 'images/93.png',
        description:
            'Vintage-wash heavyweight tank with the Twin Faces print — two icons, one duality. Soft-touch cotton, dropped armholes and a relaxed streetwear cut.',
        details: {
            Material: '240GSM washed cotton',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'forest-two-tone-long-sleeve': {
        id: 'forest-two-tone-long-sleeve',
        name: 'Forest Two-Tone',
        tag: 'Long Sleeve',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 15000,
        image: 'images/101.png',
        backImage: 'images/102.png',
        completewear: 'images/Completewear/66.png',
        badge: 'New',
        description:
            'Forest green body, midnight black sleeves — a contrast long sleeve carrying the FakeSmile brick crest at chest. Heavyweight knit, ribbed cuffs, built for layering.',
        details: {
            Material: '300GSM heavyweight cotton',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'steel-brick-hoodie': {
        id: 'steel-brick-hoodie',
        name: 'Steel Brick',
        tag: 'Hoodie',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 18000,
        image: 'images/58.png',
        backImage: 'images/59.png',
        completewear: 'images/Completewear/47.png',
        partner: 'heather-stone-joggers',
        description:
            'Steel-gray heavyweight hoodie with the FakeSmile brick crest. Brushed-back fleece, ribbed cuffs and metal-tipped drawstrings — neutral fit, loud silhouette.',
        details: {
            Material: '320GSM heavyweight cotton, brushed back',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'ash-court-jersey': {
        id: 'ash-court-jersey',
        name: 'Ash Court',
        tag: 'Jersey',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 12500,
        image: 'images/68.png',
        backImage: 'images/69.png',
        badge: 'Limited',
        description:
            'Ash-grey performance jersey with reflective trim. Breathable polyester tricot, embroidered FakeSmile crest and the "FAKE A SMILE" wordmark — built for motion.',
        details: {
            Material: 'Lightweight breathable polyester tricot',
            Fit: 'Athletic, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash, do not iron print',
            Origin: 'Crafted in Lagos',
        },
    },
    'smoke-faces-tank': {
        id: 'smoke-faces-tank',
        name: 'Smoke Faces',
        tag: 'Tank',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 9500,
        image: 'images/83.png',
        backImage: 'images/84.png',
        description:
            'Smoke-grey vintage-wash tank with the Twin Faces graphic. Soft-touch heavyweight cotton, dropped armholes and a relaxed streetwear cut.',
        details: {
            Material: '240GSM washed cotton',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'sage-two-tone-long-sleeve': {
        id: 'sage-two-tone-long-sleeve',
        name: 'Sage Two-Tone',
        tag: 'Long Sleeve',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 15000,
        image: 'images/95.png',
        backImage: 'images/96.png',
        description:
            'Sage body, midnight sleeves. Contrast long sleeve carrying the FakeSmile brick crest at chest, ribbed cuffs and a heavyweight knit feel.',
        details: {
            Material: '300GSM heavyweight cotton',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'ivory-two-tone-long-sleeve': {
        id: 'ivory-two-tone-long-sleeve',
        name: 'Ivory Two-Tone',
        tag: 'Long Sleeve',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 15000,
        image: 'images/98.png',
        backImage: 'images/99.png',
        completewear: 'images/Completewear/68.png',
        badge: 'New',
        description:
            'Ivory body, sand sleeves — a soft-tone contrast long sleeve with the FakeSmile crest. Heavyweight knit, ribbed cuffs, premium pre-shrunk cotton.',
        details: {
            Material: '300GSM heavyweight cotton',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'cream-brick-hoodie': {
        id: 'cream-brick-hoodie',
        name: 'Cream Brick',
        tag: 'Hoodie',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 18000,
        image: 'images/104.png',
        backImage: 'images/105.png',
        description:
            'Cream-tan heavyweight hoodie with the FakeSmile brick crest. Brushed inner, ribbed cuffs and metal-tipped drawstrings — the neutral hoodie that pairs with every fit.',
        details: {
            Material: '320GSM heavyweight cotton, brushed back',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'crimson-brick-hoodie': {
        id: 'crimson-brick-hoodie',
        name: 'Crimson Brick',
        tag: 'Hoodie',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 18000,
        image: 'images/107.png',
        backImage: 'images/108.png',
        badge: 'Limited',
        description:
            'Crimson-red heavyweight hoodie with the signature brick crest. Brushed cotton-fleece interior, ribbed cuffs and metal-tipped drawstrings — the loudest pull in the rotation.',
        details: {
            Material: '320GSM heavyweight cotton, brushed back',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },

    /* ===== STATEMENT SERIES (Front & Back) ===== */
    'onyx-anthem-tee': {
        id: 'onyx-anthem-tee',
        name: 'Onyx Anthem',
        tag: 'Tee',
        category: 'Statement Tops',
        categoryHash: 'tops',
        price: 15000,
        image: 'images/Tops F&B/2.png',
        backImage: 'images/Tops F&B/3.png',
        completewear: 'images/Completewear/4.png',
        badge: 'New',
        description:
            'Heavyweight midnight tee carrying the FakeSmile crest at chest and the signature graffiti script across the back. Two views, one statement.',
        details: {
            Material: '260GSM heavyweight cotton',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'cloud-anthem-tee': {
        id: 'cloud-anthem-tee',
        name: 'Cloud Anthem',
        tag: 'Tee',
        category: 'Statement Tops',
        categoryHash: 'tops',
        price: 15000,
        image: 'images/Tops F&B/5.png',
        backImage: 'images/Tops F&B/6.png',
        completewear: 'images/Completewear/7.png',
        description:
            'Cloud-white heavyweight tee with the FakeSmile crest front and the signature print across the back. Premium-feel cotton, double-stitched seams.',
        details: {
            Material: '260GSM heavyweight cotton',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'sunset-echo-crewneck': {
        id: 'sunset-echo-crewneck',
        name: 'Sunset Echo',
        tag: 'Crewneck',
        category: 'Statement Tops',
        categoryHash: 'tops',
        price: 18000,
        image: 'images/Tops F&B/8.png',
        backImage: 'images/Tops F&B/9.png',
        completewear: 'images/Completewear/10.png',
        badge: 'Bestseller',
        description:
            'Sunset-orange crewneck with brushed inner. Brick crest at chest, signature wordmark across the back — heavyweight cotton-blend fleece.',
        details: {
            Material: '320GSM cotton-blend fleece',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'midnight-echo-crewneck': {
        id: 'midnight-echo-crewneck',
        name: 'Midnight Echo',
        tag: 'Crewneck',
        category: 'Statement Tops',
        categoryHash: 'tops',
        price: 18000,
        image: 'images/Tops F&B/11.png',
        backImage: 'images/Tops F&B/12.png',
        completewear: 'images/Completewear/13.png',
        description:
            'Midnight-black crewneck. Brushed-back fleece, FakeSmile crest at chest and the signature script across the back.',
        details: {
            Material: '320GSM cotton-blend fleece',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'forest-anthem-tee': {
        id: 'forest-anthem-tee',
        name: 'Forest Anthem',
        tag: 'Tee',
        category: 'Statement Tops',
        categoryHash: 'tops',
        price: 15000,
        image: 'images/Tops F&B/14.png',
        backImage: 'images/Tops F&B/15.png',
        completewear: 'images/Completewear/16.png',
        badge: 'Limited',
        description:
            'Forest-green heavyweight tee with the FakeSmile brick crest and signature back graphic. Premium pre-shrunk cotton.',
        details: {
            Material: '260GSM heavyweight cotton',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'stone-anthem-tee': {
        id: 'stone-anthem-tee',
        name: 'Stone Anthem',
        tag: 'Tee',
        category: 'Statement Tops',
        categoryHash: 'tops',
        price: 15000,
        image: 'images/Tops F&B/17.png',
        backImage: 'images/Tops F&B/18.png',
        completewear: 'images/Completewear/19.png',
        description:
            'Stone-cream heavyweight tee with the signature crest front and full-width graphic across the back. Premium-feel cotton, built to last.',
        details: {
            Material: '260GSM heavyweight cotton',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'crimson-anthem-tee': {
        id: 'crimson-anthem-tee',
        name: 'Crimson Anthem',
        tag: 'Tee',
        category: 'Statement Tops',
        categoryHash: 'tops',
        price: 15000,
        image: 'images/Tops F&B/20.png',
        backImage: 'images/Tops F&B/21.png',
        completewear: 'images/Completewear/22.png',
        badge: 'New',
        description:
            'Crimson-red heavyweight tee with the FakeSmile crest front and signature script back. The loudest piece in the rotation.',
        details: {
            Material: '260GSM heavyweight cotton',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'sand-echo-crewneck': {
        id: 'sand-echo-crewneck',
        name: 'Sand Echo',
        tag: 'Crewneck',
        category: 'Statement Tops',
        categoryHash: 'tops',
        price: 18000,
        image: 'images/Tops F&B/23.png',
        backImage: 'images/Tops F&B/24.png',
        completewear: 'images/Completewear/25.png',
        description:
            'Sand-tan crewneck with brushed inner and signature graphic across the back. Heavyweight cotton-blend fleece — the neutral pairer for every fit.',
        details: {
            Material: '320GSM cotton-blend fleece',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'charcoal-anthem-tee': {
        id: 'charcoal-anthem-tee',
        name: 'Charcoal Anthem',
        tag: 'Tee',
        category: 'Statement Tops',
        categoryHash: 'tops',
        price: 15000,
        image: 'images/Tops F&B/26.png',
        backImage: 'images/Tops F&B/27.png',
        completewear: 'images/Completewear/28.png',
        description:
            'Charcoal heavyweight tee with the FakeSmile crest front and signature script across the back. Premium-feel cotton, double-stitched seams.',
        details: {
            Material: '260GSM heavyweight cotton',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'olive-anthem-tee': {
        id: 'olive-anthem-tee',
        name: 'Olive Anthem',
        tag: 'Tee',
        category: 'Statement Tops',
        categoryHash: 'tops',
        price: 15000,
        image: 'images/Tops F&B/38.png',
        badge: 'New',
        description:
            'Olive heavyweight tee with the FakeSmile patchwork stack at chest. Pre-shrunk premium cotton, double-stitched seams, relaxed streetwear cut.',
        details: {
            Material: '260GSM heavyweight cotton',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'onyx-stack-tee': {
        id: 'onyx-stack-tee',
        name: 'Onyx Stack',
        tag: 'Tee',
        category: 'Statement Tops',
        categoryHash: 'tops',
        price: 15000,
        image: 'images/Tops F&B/39.png',
        description:
            'Onyx-black heavyweight tee carrying the FakeSmile patchwork stack — multi-icon graphic, signature script and a relaxed streetwear cut.',
        details: {
            Material: '260GSM heavyweight cotton',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'storm-anthem-tee': {
        id: 'storm-anthem-tee',
        name: 'Storm Anthem',
        tag: 'Tee',
        category: 'Statement Tops',
        categoryHash: 'tops',
        price: 15000,
        image: 'images/Tops F&B/40.png',
        description:
            'Forest-green heavyweight tee with the FakeSmile patchwork stack at chest. Pre-shrunk premium cotton — soft, loud, built to last.',
        details: {
            Material: '260GSM heavyweight cotton',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'mist-stack-tee': {
        id: 'mist-stack-tee',
        name: 'Mist Stack',
        tag: 'Tee',
        category: 'Statement Tops',
        categoryHash: 'tops',
        price: 15000,
        image: 'images/Tops F&B/41.png',
        description:
            'Mist heavyweight tee with the FakeSmile patchwork stack — multi-icon graphic on premium pre-shrunk cotton. A neutral pairer for any fit.',
        details: {
            Material: '260GSM heavyweight cotton',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    /* ===== BOTTOMS ===== */
    'sunset-signature-joggers': {
        id: 'sunset-signature-joggers',
        name: 'Sunset Signature',
        tag: 'Joggers',
        category: 'Joggers & Shorts',
        categoryHash: 'bottoms',
        price: 14500,
        image: 'images/47.png',
        completewear: 'images/Completewear/44.png',
        partner: 'sunset-brick-hoodie',
        badge: 'New',
        description:
            'Sunset-orange signature joggers with the side-leg "FAKE A SMILE" graffiti script. Soft-touch fleece interior, elastic waist with drawstring and ribbed ankle cuffs.',
        details: {
            Material: '320GSM cotton-blend fleece',
            Fit: 'Tapered, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, tumble low',
            Origin: 'Crafted in Lagos',
        },
    },
    'cloud-signature-joggers': {
        id: 'cloud-signature-joggers',
        name: 'Cloud Signature',
        tag: 'Joggers',
        category: 'Joggers & Shorts',
        categoryHash: 'bottoms',
        price: 14500,
        image: 'images/51.png',
        completewear: 'images/Completewear/45.png',
        partner: 'cloud-brick-hoodie',
        description:
            'Crisp cloud-white joggers with the signature graffiti script along the side leg. Premium-feel fleece, deep side pockets and a tailored taper.',
        details: {
            Material: '320GSM cotton-blend fleece',
            Fit: 'Tapered, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, tumble low',
            Origin: 'Crafted in Lagos',
        },
    },
    'midnight-signature-joggers': {
        id: 'midnight-signature-joggers',
        name: 'Midnight Signature',
        tag: 'Joggers',
        category: 'Joggers & Shorts',
        categoryHash: 'bottoms',
        price: 14500,
        image: 'images/55.png',
        completewear: 'images/Completewear/46.png',
        partner: 'midnight-brick-hoodie',
        badge: 'Bestseller',
        description:
            'The original midnight-black signature joggers. Heavy fleece, signature side script, perfect taper — the most-worn drop in the catalog.',
        details: {
            Material: '320GSM cotton-blend fleece',
            Fit: 'Tapered, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, tumble low',
            Origin: 'Crafted in Lagos',
        },
    },
    'heather-stone-joggers': {
        id: 'heather-stone-joggers',
        name: 'Heather Stone',
        tag: 'Joggers',
        category: 'Joggers & Shorts',
        categoryHash: 'bottoms',
        price: 14500,
        image: 'images/60.png',
        completewear: 'images/Completewear/47.png',
        partner: 'steel-brick-hoodie',
        description:
            'Heather-grey joggers with chrome-foil signature script — the everyday utility cut. Soft brushed fleece, drawstring waist, deep pockets.',
        details: {
            Material: '320GSM cotton-blend fleece',
            Fit: 'Tapered, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, tumble low',
            Origin: 'Crafted in Lagos',
        },
    },
    'crimson-court-shorts': {
        id: 'crimson-court-shorts',
        name: 'Crimson Court',
        tag: 'Shorts',
        category: 'Joggers & Shorts',
        categoryHash: 'bottoms',
        price: 9500,
        image: 'images/65.png',
        completewear: 'images/Completewear/49.png',
        partner: 'crimson-court-jersey',
        badge: 'Limited',
        description:
            'Crimson court shorts with white trim, mesh-lined for breathable everyday wear. The off-court take on the matching jersey.',
        details: {
            Material: 'Lightweight polyester, mesh-lined',
            Fit: 'Standard, true-to-size',
            Sizes: 'S / M / L / XL',
            Care: 'Cold wash, do not iron',
            Origin: 'Crafted in Lagos',
        },
    },
    'forest-court-shorts': {
        id: 'forest-court-shorts',
        name: 'Forest Court',
        tag: 'Shorts',
        category: 'Joggers & Shorts',
        categoryHash: 'bottoms',
        price: 9500,
        image: 'images/70.png',
        completewear: 'images/Completewear/51.png',
        description:
            'Forest-green court shorts with embroidered FakeSmile brick crest. Mesh-lined, drawstring elastic waist, signature off-court fit.',
        details: {
            Material: 'Lightweight polyester, mesh-lined',
            Fit: 'Standard, true-to-size',
            Sizes: 'S / M / L / XL',
            Care: 'Cold wash, do not iron',
            Origin: 'Crafted in Lagos',
        },
    },
    'cloud-stripe-shorts': {
        id: 'cloud-stripe-shorts',
        name: 'Cloud Stripe',
        tag: 'Shorts',
        category: 'Joggers & Shorts',
        categoryHash: 'bottoms',
        price: 9500,
        image: 'images/75.png',
        completewear: 'images/Completewear/53.png',
        description:
            'Cloud-white shorts with signature crimson stripes and waistband. Lightweight, breathable, and easy to pair top-to-bottom.',
        details: {
            Material: 'Lightweight polyester, mesh-lined',
            Fit: 'Standard, true-to-size',
            Sizes: 'S / M / L / XL',
            Care: 'Cold wash, do not iron',
            Origin: 'Crafted in Lagos',
        },
    },
    'onyx-gold-shorts': {
        id: 'onyx-gold-shorts',
        name: 'Onyx Gold',
        tag: 'Shorts',
        category: 'Joggers & Shorts',
        categoryHash: 'bottoms',
        price: 9500,
        image: 'images/80.png',
        completewear: 'images/Completewear/55.png',
        partner: 'onyx-gold-jersey',
        badge: 'New',
        description:
            'Black-and-gold court shorts to complete the Onyx Gold set. Lightweight tricot, drawstring waist and signature gold trim.',
        details: {
            Material: 'Lightweight polyester, mesh-lined',
            Fit: 'Standard, true-to-size',
            Sizes: 'S / M / L / XL',
            Care: 'Cold wash, do not iron',
            Origin: 'Crafted in Lagos',
        },
    },
    'smoke-court-shorts': {
        id: 'smoke-court-shorts',
        name: 'Smoke Court',
        tag: 'Shorts',
        category: 'Joggers & Shorts',
        categoryHash: 'bottoms',
        price: 9500,
        image: 'images/73.png',
        backImage: 'images/74.png',
        description:
            'Smoke-grey court shorts with reflective trim. Mesh-lined polyester, drawstring elastic waist and the off-court signature fit.',
        details: {
            Material: 'Lightweight polyester, mesh-lined',
            Fit: 'Standard, true-to-size',
            Sizes: 'S / M / L / XL',
            Care: 'Cold wash, do not iron',
            Origin: 'Crafted in Lagos',
        },
    },

    /* ===== HEADWEAR ===== */
    'sunshine-bucket-hat': {
        id: 'sunshine-bucket-hat',
        name: 'Sunshine',
        tag: 'Bucket Hat',
        category: 'Headwear',
        categoryHash: 'headwear',
        price: 7500,
        image: 'images/62.png',
        badge: 'New',
        description:
            'Sun-yellow bucket hat in heavy cotton twill with the FakeSmile brick crest at the front panel. The finishing piece on a loud fit.',
        details: {
            Material: 'Heavy cotton twill',
            Fit: 'One size, adjustable inner band',
            Sizes: 'OS · 56–60cm',
            Care: 'Spot clean only',
            Origin: 'Crafted in Lagos',
        },
    },
    'midnight-bucket-hat': {
        id: 'midnight-bucket-hat',
        name: 'Midnight',
        tag: 'Bucket Hat',
        category: 'Headwear',
        categoryHash: 'headwear',
        price: 7500,
        image: 'images/61.png',
        badge: 'Bestseller',
        description:
            'Midnight-black bucket hat with embroidered FakeSmile crest. Cotton twill, structured brim and a signature streetwear silhouette.',
        details: {
            Material: 'Heavy cotton twill',
            Fit: 'One size, adjustable inner band',
            Sizes: 'OS · 56–60cm',
            Care: 'Spot clean only',
            Origin: 'Crafted in Lagos',
        },
    },
    'stone-bucket-hat': {
        id: 'stone-bucket-hat',
        name: 'Stone',
        tag: 'Bucket Hat',
        category: 'Headwear',
        categoryHash: 'headwear',
        price: 7500,
        image: 'images/596.png',
        description:
            'Stone-cream bucket hat in heavy cotton twill with the FakeSmile crest. Neutral, premium, and pairs with every drop in the catalog.',
        details: {
            Material: 'Heavy cotton twill',
            Fit: 'One size, adjustable inner band',
            Sizes: 'OS · 56–60cm',
            Care: 'Spot clean only',
            Origin: 'Crafted in Lagos',
        },
    },
    'crimson-bucket-hat': {
        id: 'crimson-bucket-hat',
        name: 'Crimson',
        tag: 'Bucket Hat',
        category: 'Headwear',
        categoryHash: 'headwear',
        price: 7500,
        image: 'images/650.png',
        badge: 'Limited',
        description:
            'Crimson-red bucket hat with the FakeSmile brick crest. Heavy cotton twill, structured brim — the loudest finish on a court fit.',
        details: {
            Material: 'Heavy cotton twill',
            Fit: 'One size, adjustable inner band',
            Sizes: 'OS · 56–60cm',
            Care: 'Spot clean only',
            Origin: 'Crafted in Lagos',
        },
    },
    'ash-bucket-hat': {
        id: 'ash-bucket-hat',
        name: 'Ash',
        tag: 'Bucket Hat',
        category: 'Headwear',
        categoryHash: 'headwear',
        price: 7500,
        image: 'images/85.png',
        badge: 'New',
        description:
            'Ash-grey bucket hat in heavy cotton twill with the FakeSmile crest. Neutral, premium, and the easiest finish on any fit.',
        details: {
            Material: 'Heavy cotton twill',
            Fit: 'One size, adjustable inner band',
            Sizes: 'OS · 56–60cm',
            Care: 'Spot clean only',
            Origin: 'Crafted in Lagos',
        },
    },
};

/** Look up a product by id, returning null if not found. */
function getProduct(id) {
    return id && PRODUCTS[id] ? PRODUCTS[id] : null;
}

/** Return up to N other products (excluding the given id), preferring same category. */
function getRelatedProducts(id, n) {
    n = n || 4;
    const current = getProduct(id);
    if (!current) return Object.values(PRODUCTS).slice(0, n);
    const sameCat = [];
    const others = [];
    Object.values(PRODUCTS).forEach((p) => {
        if (p.id === id) return;
        if (p.category === current.category) sameCat.push(p);
        else others.push(p);
    });
    return sameCat.concat(others).slice(0, n);
}
