/* ============================================= */
/* === PRODUCTS DATA (shared catalog) ========== */
/* ============================================= */

const PRODUCTS = {
    /* ===== TOPS & HOODIES ===== */
    'sunset-brick-hoodie': {
        id: 'sunset-brick-hoodie',
        name: 'Sunset Brick',
        tag: 'Hoodie',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 18000,
        image: 'images/45.webp',
        backImage: 'images/46.webp',
        completewear: 'images/Completewear/44.webp',
        partner: 'sunset-signature-joggers',
        badge: 'New',
        description:
            'Heavyweight 320GSM cotton hoodie finished in sunset orange and anchored by the FakeSmile brick crest. Pre-shrunk, double-stitched, with metal-tipped drawstrings and a kangaroo pocket — engineered to outlast the drop.',
        details: {
            Material: '320GSM heavyweight cotton, brushed back',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'cloud-brick-hoodie': {
        id: 'cloud-brick-hoodie',
        name: 'Cloud Brick',
        tag: 'Hoodie',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 18000,
        image: 'images/49.webp',
        backImage: 'images/50.webp',
        completewear: 'images/Completewear/45.webp',
        partner: 'cloud-signature-joggers',
        description:
            'Cloud-white 320GSM cotton hoodie carrying the FakeSmile brick crest in muted contrast. Premium-feel brushed inner, ribbed cuffs and a streetwear-ready relaxed fit.',
        details: {
            Material: '320GSM heavyweight cotton, brushed back',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'midnight-brick-hoodie': {
        id: 'midnight-brick-hoodie',
        name: 'Midnight Brick',
        tag: 'Hoodie',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 18000,
        image: 'images/53.webp',
        backImage: 'images/54.webp',
        completewear: 'images/Completewear/46.webp',
        partner: 'midnight-signature-joggers',
        badge: 'Bestseller',
        description:
            'The signature midnight-black hoodie. Heavyweight cotton, FakeSmile brick crest, double-stitched cuffs and metal-tipped drawstrings — the most-pulled fit in the wardrobe.',
        details: {
            Material: '320GSM heavyweight cotton, brushed back',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'crimson-court-jersey': {
        id: 'crimson-court-jersey',
        name: 'Crimson Court',
        tag: 'Jersey',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 12500,
        image: 'images/63.webp',
        backImage: 'images/64.webp',
        completewear: 'images/Completewear/49.webp',
        partner: 'crimson-court-shorts',
        description:
            'Court-ready performance jersey in crimson with white trim. Lightweight breathable mesh tricot and the "FAKE A SMILE" wordmark — engineered for motion.',
        details: {
            Material: 'Lightweight breathable polyester tricot',
            Fit: 'Athletic, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash, do not iron print',
            Origin: 'Crafted in Lagos',
        },
    },
    'onyx-gold-jersey': {
        id: 'onyx-gold-jersey',
        name: 'Onyx Gold',
        tag: 'Jersey',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 12500,
        image: 'images/78.webp',
        backImage: 'images/79.webp',
        completewear: 'images/Completewear/55.webp',
        partner: 'onyx-gold-shorts',
        badge: 'Limited',
        description:
            'Black-on-gold jersey with embroidered FakeSmile crest. Lightweight tricot, breathable mesh side panels and signature ribbed collar — limited run.',
        details: {
            Material: 'Lightweight breathable polyester tricot',
            Fit: 'Athletic, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash, do not iron print',
            Origin: 'Crafted in Lagos',
        },
    },
    'twin-faces-tank': {
        id: 'twin-faces-tank',
        name: 'Twin Faces',
        tag: 'Tank',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 9500,
        image: 'images/92.webp',
        backImage: 'images/93.webp',
        completewear: 'images/Completewear/63.webp',
        description:
            'Vintage-wash heavyweight tank with the Twin Faces print — two icons, one duality. Soft-touch cotton, dropped armholes and a relaxed streetwear cut.',
        details: {
            Material: '240GSM washed cotton',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'cream-faces-tank': {
        id: 'cream-faces-tank',
        name: 'Cream Faces',
        tag: 'Tank',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 9500,
        image: 'images/98.webp',
        backImage: 'images/99.webp',
        completewear: 'images/Completewear/65.webp',
        badge: 'New',
        description:
            'Cream-sand vintage-wash tank with the FakeSmile statement graphic. Soft-touch heavyweight cotton, dropped armholes and a relaxed streetwear cut.',
        details: {
            Material: '240GSM washed cotton',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'forest-two-tone-long-sleeve': {
        id: 'forest-two-tone-long-sleeve',
        name: 'Forest Two-Tone',
        tag: 'Long Sleeve',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 15000,
        image: 'images/101.webp',
        backImage: 'images/102.webp',
        completewear: 'images/Completewear/66.webp',
        badge: 'New',
        description:
            'Forest green body, ivory contrast sleeves — a two-tone long sleeve carrying the FakeSmile brick crest at chest. Heavyweight knit, ribbed cuffs, built for layering.',
        details: {
            Material: '300GSM heavyweight cotton',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'onyx-two-tone-long-sleeve': {
        id: 'onyx-two-tone-long-sleeve',
        name: 'Onyx Two-Tone',
        tag: 'Long Sleeve',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 15000,
        image: 'images/104.webp',
        backImage: 'images/105.webp',
        completewear: 'images/Completewear/67.webp',
        badge: 'Bestseller',
        description:
            'Midnight-black body, ivory contrast sleeves. Heavyweight knit, ribbed cuffs and the FakeSmile crest at chest — the loudest layering piece in the rotation.',
        details: {
            Material: '300GSM heavyweight cotton',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'steel-brick-hoodie': {
        id: 'steel-brick-hoodie',
        name: 'Steel Brick',
        tag: 'Hoodie',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 18000,
        image: 'images/58.webp',
        backImage: 'images/59.webp',
        completewear: 'images/Completewear/47.webp',
        partner: 'heather-stone-joggers',
        description:
            'Steel-gray heavyweight hoodie with the FakeSmile brick crest. Brushed-back fleece, ribbed cuffs and metal-tipped drawstrings — neutral fit, loud silhouette.',
        details: {
            Material: '320GSM heavyweight cotton, brushed back',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'forest-court-jersey': {
        id: 'forest-court-jersey',
        name: 'Forest Court',
        tag: 'Jersey',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 12500,
        image: 'images/68.webp',
        backImage: 'images/69.webp',
        completewear: 'images/Completewear/51.webp',
        partner: 'forest-court-shorts',
        badge: 'New',
        description:
            'Forest-green performance jersey with white trim. Lightweight breathable mesh tricot and the "FAKE A SMILE" wordmark — engineered for motion.',
        details: {
            Material: 'Lightweight breathable polyester tricot',
            Fit: 'Athletic, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash, do not iron print',
            Origin: 'Crafted in Lagos',
        },
    },
    'cloud-court-jersey': {
        id: 'cloud-court-jersey',
        name: 'Cloud Court',
        tag: 'Jersey',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 12500,
        image: 'images/73.webp',
        backImage: 'images/74.webp',
        completewear: 'images/Completewear/53.webp',
        partner: 'cloud-stripe-shorts',
        description:
            'Cloud-white performance jersey with crimson trim. Lightweight breathable mesh tricot, embroidered FakeSmile crest and the "FAKE A SMILE" wordmark.',
        details: {
            Material: 'Lightweight breathable polyester tricot',
            Fit: 'Athletic, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash, do not iron print',
            Origin: 'Crafted in Lagos',
        },
    },
    'sunset-court-jersey': {
        id: 'sunset-court-jersey',
        name: 'Sunset Court',
        tag: 'Jersey',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 12500,
        image: 'images/83.webp',
        backImage: 'images/84.webp',
        completewear: 'images/Completewear/57.webp',
        partner: 'sunset-court-shorts',
        badge: 'Limited',
        description:
            'Sunset-orange performance jersey with the "FAKE A SMILE" wordmark across the chest. Lightweight breathable tricot — the loudest fit on the court.',
        details: {
            Material: 'Lightweight breathable polyester tricot',
            Fit: 'Athletic, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash, do not iron print',
            Origin: 'Crafted in Lagos',
        },
    },
    'ivory-two-tone-long-sleeve': {
        id: 'ivory-two-tone-long-sleeve',
        name: 'Ivory Two-Tone',
        tag: 'Long Sleeve',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 15000,
        image: 'images/107.webp',
        backImage: 'images/108.webp',
        completewear: 'images/Completewear/68.webp',
        badge: 'New',
        description:
            'Ivory body, midnight contrast sleeves — a soft-tone two-tone long sleeve carrying the FakeSmile crest at chest. Heavyweight knit, ribbed cuffs, premium pre-shrunk cotton.',
        details: {
            Material: '300GSM heavyweight cotton',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'shadow-crest-hoodie': {
        id: 'shadow-crest-hoodie',
        name: 'Shadow Crest',
        tag: 'Hoodie',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 18000,
        image: 'images/119.webp',
        badge: 'New',
        description:
            'Pitch-black heavyweight hoodie carrying the FakeSmile crest at chest. Brushed-back fleece, ribbed cuffs and metal-tipped drawstrings — clean silhouette, loud quality.',
        details: {
            Material: '320GSM heavyweight cotton, brushed back',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'heather-crest-hoodie': {
        id: 'heather-crest-hoodie',
        name: 'Heather Crest',
        tag: 'Hoodie',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 18000,
        image: 'images/189.webp',
        description:
            'Heathered grey heavyweight hoodie with the FakeSmile crest at chest. Brushed cotton-fleece interior, ribbed cuffs — the neutral pull that pairs with every fit.',
        details: {
            Material: '320GSM heavyweight cotton, brushed back',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'pearl-crest-hoodie': {
        id: 'pearl-crest-hoodie',
        name: 'Pearl Crest',
        tag: 'Hoodie',
        category: 'Tops & Hoodies',
        categoryHash: 'products',
        price: 18000,
        image: 'images/190.webp',
        badge: 'New',
        description:
            'Pearl-white heavyweight hoodie carrying the FakeSmile crest at chest. Premium brushed inner, ribbed cuffs and metal-tipped drawstrings — clean, premium, signature.',
        details: {
            Material: '320GSM heavyweight cotton, brushed back',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },

    /* ===== STATEMENT SERIES (Front & Back) ===== */
    'onyx-anthem-tee': {
        id: 'onyx-anthem-tee',
        name: 'Onyx Anthem',
        tag: 'Tee',
        category: 'Statement Tops',
        categoryHash: 'tops',
        price: 15000,
        image: 'images/Tops F&B/2.webp',
        backImage: 'images/Tops F&B/3.webp',
        completewear: 'images/Completewear/4.webp',
        badge: 'New',
        description:
            'Heavyweight midnight tee carrying the FakeSmile crest at chest and the signature graffiti script across the back. Two views, one statement.',
        details: {
            Material: '260GSM heavyweight cotton',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'cloud-anthem-tee': {
        id: 'cloud-anthem-tee',
        name: 'Cloud Anthem',
        tag: 'Tee',
        category: 'Statement Tops',
        categoryHash: 'tops',
        price: 15000,
        image: 'images/Tops F&B/5.webp',
        backImage: 'images/Tops F&B/6.webp',
        completewear: 'images/Completewear/7.webp',
        description:
            'Cloud-white heavyweight tee with the FakeSmile crest front and the signature print across the back. Premium-feel cotton, double-stitched seams.',
        details: {
            Material: '260GSM heavyweight cotton',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'sunset-echo-crewneck': {
        id: 'sunset-echo-crewneck',
        name: 'Sunset Echo',
        tag: 'Crewneck',
        category: 'Statement Tops',
        categoryHash: 'tops',
        price: 18000,
        image: 'images/Tops F&B/8.webp',
        backImage: 'images/Tops F&B/9.webp',
        completewear: 'images/Completewear/10.webp',
        badge: 'Bestseller',
        description:
            'Sunset-orange crewneck with brushed inner. Brick crest at chest, signature wordmark across the back — heavyweight cotton-blend fleece.',
        details: {
            Material: '320GSM cotton-blend fleece',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'midnight-echo-crewneck': {
        id: 'midnight-echo-crewneck',
        name: 'Midnight Echo',
        tag: 'Crewneck',
        category: 'Statement Tops',
        categoryHash: 'tops',
        price: 18000,
        image: 'images/Tops F&B/11.webp',
        backImage: 'images/Tops F&B/12.webp',
        completewear: 'images/Completewear/13.webp',
        description:
            'Midnight-black crewneck. Brushed-back fleece, FakeSmile crest at chest and the signature script across the back.',
        details: {
            Material: '320GSM cotton-blend fleece',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'forest-anthem-tee': {
        id: 'forest-anthem-tee',
        name: 'Forest Anthem',
        tag: 'Tee',
        category: 'Statement Tops',
        categoryHash: 'tops',
        price: 15000,
        image: 'images/Tops F&B/14.webp',
        backImage: 'images/Tops F&B/15.webp',
        completewear: 'images/Completewear/16.webp',
        badge: 'Limited',
        description:
            'Forest-green heavyweight tee with the FakeSmile brick crest and signature back graphic. Premium pre-shrunk cotton.',
        details: {
            Material: '260GSM heavyweight cotton',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'stone-anthem-tee': {
        id: 'stone-anthem-tee',
        name: 'Stone Anthem',
        tag: 'Tee',
        category: 'Statement Tops',
        categoryHash: 'tops',
        price: 15000,
        image: 'images/Tops F&B/17.webp',
        backImage: 'images/Tops F&B/18.webp',
        completewear: 'images/Completewear/19.webp',
        description:
            'Stone-cream heavyweight tee with the signature crest front and full-width graphic across the back. Premium-feel cotton, built to last.',
        details: {
            Material: '260GSM heavyweight cotton',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'crimson-anthem-tee': {
        id: 'crimson-anthem-tee',
        name: 'Crimson Anthem',
        tag: 'Tee',
        category: 'Statement Tops',
        categoryHash: 'tops',
        price: 15000,
        image: 'images/Tops F&B/20.webp',
        backImage: 'images/Tops F&B/21.webp',
        completewear: 'images/Completewear/22.webp',
        badge: 'New',
        description:
            'Crimson-red heavyweight tee with the FakeSmile crest front and signature script back. The loudest piece in the rotation.',
        details: {
            Material: '260GSM heavyweight cotton',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'sand-echo-crewneck': {
        id: 'sand-echo-crewneck',
        name: 'Sand Echo',
        tag: 'Crewneck',
        category: 'Statement Tops',
        categoryHash: 'tops',
        price: 18000,
        image: 'images/Tops F&B/23.webp',
        backImage: 'images/Tops F&B/24.webp',
        completewear: 'images/Completewear/25.webp',
        description:
            'Sand-tan crewneck with brushed inner and signature graphic across the back. Heavyweight cotton-blend fleece — the neutral pairer for every fit.',
        details: {
            Material: '320GSM cotton-blend fleece',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'charcoal-anthem-tee': {
        id: 'charcoal-anthem-tee',
        name: 'Charcoal Anthem',
        tag: 'Tee',
        category: 'Statement Tops',
        categoryHash: 'tops',
        price: 15000,
        image: 'images/Tops F&B/26.webp',
        backImage: 'images/Tops F&B/27.webp',
        completewear: 'images/Completewear/28.webp',
        description:
            'Charcoal heavyweight tee with the FakeSmile crest front and signature script across the back. Premium-feel cotton, double-stitched seams.',
        details: {
            Material: '260GSM heavyweight cotton',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    /* ===== TEMPORARILY HIDDEN — uncomment this whole block to relist these tees =====
    'olive-anthem-tee': {
        id: 'olive-anthem-tee',
        name: 'Olive Anthem',
        tag: 'Tee',
        category: 'Statement Tops',
        categoryHash: 'tops',
        price: 15000,
        image: 'images/Tops F&B/38.webp',
        badge: 'New',
        description:
            'Olive heavyweight tee with the FakeSmile patchwork stack at chest. Pre-shrunk premium cotton, double-stitched seams, relaxed streetwear cut.',
        details: {
            Material: '260GSM heavyweight cotton',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'onyx-stack-tee': {
        id: 'onyx-stack-tee',
        name: 'Onyx Stack',
        tag: 'Tee',
        category: 'Statement Tops',
        categoryHash: 'tops',
        price: 15000,
        image: 'images/Tops F&B/39.webp',
        description:
            'Onyx-black heavyweight tee carrying the FakeSmile patchwork stack — multi-icon graphic, signature script and a relaxed streetwear cut.',
        details: {
            Material: '260GSM heavyweight cotton',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'storm-anthem-tee': {
        id: 'storm-anthem-tee',
        name: 'Storm Anthem',
        tag: 'Tee',
        category: 'Statement Tops',
        categoryHash: 'tops',
        price: 15000,
        image: 'images/Tops F&B/40.webp',
        description:
            'Forest-green heavyweight tee with the FakeSmile patchwork stack at chest. Pre-shrunk premium cotton — soft, loud, built to last.',
        details: {
            Material: '260GSM heavyweight cotton',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    'mist-stack-tee': {
        id: 'mist-stack-tee',
        name: 'Mist Stack',
        tag: 'Tee',
        category: 'Statement Tops',
        categoryHash: 'tops',
        price: 15000,
        image: 'images/Tops F&B/41.webp',
        description:
            'Mist heavyweight tee with the FakeSmile patchwork stack — multi-icon graphic on premium pre-shrunk cotton. A neutral pairer for any fit.',
        details: {
            Material: '260GSM heavyweight cotton',
            Fit: 'Relaxed, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, hang dry',
            Origin: 'Crafted in Lagos',
        },
    },
    ===== END TEMPORARILY HIDDEN ===== */
    /* ===== BOTTOMS ===== */
    'sunset-signature-joggers': {
        id: 'sunset-signature-joggers',
        name: 'Sunset Signature',
        tag: 'Joggers',
        category: 'Joggers & Shorts',
        categoryHash: 'bottoms',
        price: 14500,
        image: 'images/47.webp',
        completewear: 'images/Completewear/44.webp',
        partner: 'sunset-brick-hoodie',
        badge: 'New',
        description:
            'Sunset-orange signature joggers with the side-leg "FAKE A SMILE" graffiti script. Soft-touch fleece interior, elastic waist with drawstring and ribbed ankle cuffs.',
        details: {
            Material: '320GSM cotton-blend fleece',
            Fit: 'Tapered, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, tumble low',
            Origin: 'Crafted in Lagos',
        },
    },
    'cloud-signature-joggers': {
        id: 'cloud-signature-joggers',
        name: 'Cloud Signature',
        tag: 'Joggers',
        category: 'Joggers & Shorts',
        categoryHash: 'bottoms',
        price: 14500,
        image: 'images/51.webp',
        completewear: 'images/Completewear/45.webp',
        partner: 'cloud-brick-hoodie',
        description:
            'Crisp cloud-white joggers with the signature graffiti script along the side leg. Premium-feel fleece, deep side pockets and a tailored taper.',
        details: {
            Material: '320GSM cotton-blend fleece',
            Fit: 'Tapered, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, tumble low',
            Origin: 'Crafted in Lagos',
        },
    },
    'midnight-signature-joggers': {
        id: 'midnight-signature-joggers',
        name: 'Midnight Signature',
        tag: 'Joggers',
        category: 'Joggers & Shorts',
        categoryHash: 'bottoms',
        price: 14500,
        image: 'images/55.webp',
        completewear: 'images/Completewear/46.webp',
        partner: 'midnight-brick-hoodie',
        badge: 'Bestseller',
        description:
            'The original midnight-black signature joggers. Heavy fleece, signature side script, perfect taper — the most-worn drop in the catalog.',
        details: {
            Material: '320GSM cotton-blend fleece',
            Fit: 'Tapered, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, tumble low',
            Origin: 'Crafted in Lagos',
        },
    },
    'heather-stone-joggers': {
        id: 'heather-stone-joggers',
        name: 'Heather Stone',
        tag: 'Joggers',
        category: 'Joggers & Shorts',
        categoryHash: 'bottoms',
        price: 14500,
        image: 'images/60.webp',
        completewear: 'images/Completewear/47.webp',
        partner: 'steel-brick-hoodie',
        description:
            'Heather-grey joggers with chrome-foil signature script — the everyday utility cut. Soft brushed fleece, drawstring waist, deep pockets.',
        details: {
            Material: '320GSM cotton-blend fleece',
            Fit: 'Tapered, true-to-size',
            Sizes: 'S / M / L / XL / XXL',
            Care: 'Cold wash inside-out, tumble low',
            Origin: 'Crafted in Lagos',
        },
    },
    'crimson-court-shorts': {
        id: 'crimson-court-shorts',
        name: 'Crimson Court',
        tag: 'Shorts',
        category: 'Joggers & Shorts',
        categoryHash: 'bottoms',
        price: 9500,
        image: 'images/65.webp',
        completewear: 'images/Completewear/49.webp',
        partner: 'crimson-court-jersey',
        badge: 'Limited',
        description:
            'Crimson court shorts with white trim, mesh-lined for breathable everyday wear. The off-court take on the matching jersey.',
        details: {
            Material: 'Lightweight polyester, mesh-lined',
            Fit: 'Standard, true-to-size',
            Sizes: 'S / M / L / XL',
            Care: 'Cold wash, do not iron',
            Origin: 'Crafted in Lagos',
        },
    },
    'forest-court-shorts': {
        id: 'forest-court-shorts',
        name: 'Forest Court',
        tag: 'Shorts',
        category: 'Joggers & Shorts',
        categoryHash: 'bottoms',
        price: 9500,
        image: 'images/70.webp',
        completewear: 'images/Completewear/51.webp',
        partner: 'forest-court-jersey',
        description:
            'Forest-green court shorts with embroidered FakeSmile brick crest. Mesh-lined, drawstring elastic waist, signature off-court fit.',
        details: {
            Material: 'Lightweight polyester, mesh-lined',
            Fit: 'Standard, true-to-size',
            Sizes: 'S / M / L / XL',
            Care: 'Cold wash, do not iron',
            Origin: 'Crafted in Lagos',
        },
    },
    'cloud-stripe-shorts': {
        id: 'cloud-stripe-shorts',
        name: 'Cloud Stripe',
        tag: 'Shorts',
        category: 'Joggers & Shorts',
        categoryHash: 'bottoms',
        price: 9500,
        image: 'images/75.webp',
        completewear: 'images/Completewear/53.webp',
        partner: 'cloud-court-jersey',
        description:
            'Cloud-white shorts with signature crimson stripes and waistband. Lightweight, breathable, and easy to pair top-to-bottom.',
        details: {
            Material: 'Lightweight polyester, mesh-lined',
            Fit: 'Standard, true-to-size',
            Sizes: 'S / M / L / XL',
            Care: 'Cold wash, do not iron',
            Origin: 'Crafted in Lagos',
        },
    },
    'sunset-court-shorts': {
        id: 'sunset-court-shorts',
        name: 'Sunset Court',
        tag: 'Shorts',
        category: 'Joggers & Shorts',
        categoryHash: 'bottoms',
        price: 9500,
        image: 'images/85.webp',
        completewear: 'images/Completewear/57.webp',
        partner: 'sunset-court-jersey',
        badge: 'Limited',
        description:
            'Sunset-orange court shorts to complete the Sunset Court set. Lightweight mesh-lined polyester, drawstring elastic waist and signature off-court fit.',
        details: {
            Material: 'Lightweight polyester, mesh-lined',
            Fit: 'Standard, true-to-size',
            Sizes: 'S / M / L / XL',
            Care: 'Cold wash, do not iron',
            Origin: 'Crafted in Lagos',
        },
    },
    'onyx-gold-shorts': {
        id: 'onyx-gold-shorts',
        name: 'Onyx Gold',
        tag: 'Shorts',
        category: 'Joggers & Shorts',
        categoryHash: 'bottoms',
        price: 9500,
        image: 'images/80.webp',
        completewear: 'images/Completewear/55.webp',
        partner: 'onyx-gold-jersey',
        badge: 'New',
        description:
            'Black-and-gold court shorts to complete the Onyx Gold set. Lightweight tricot, drawstring waist and signature gold trim.',
        details: {
            Material: 'Lightweight polyester, mesh-lined',
            Fit: 'Standard, true-to-size',
            Sizes: 'S / M / L / XL',
            Care: 'Cold wash, do not iron',
            Origin: 'Crafted in Lagos',
        },
    },
    /* ===== HEADWEAR ===== */
    'sunshine-bucket-hat': {
        id: 'sunshine-bucket-hat',
        name: 'Sunshine',
        tag: 'Bucket Hat',
        category: 'Headwear',
        categoryHash: 'headwear',
        price: 7500,
        image: 'images/62.webp',
        badge: 'New',
        description:
            'Sun-yellow bucket hat in heavy cotton twill with the FakeSmile brick crest at the front panel. The finishing piece on a loud fit.',
        details: {
            Material: 'Heavy cotton twill',
            Fit: 'One size, adjustable inner band',
            Sizes: 'OS · 56–60cm',
            Care: 'Spot clean only',
            Origin: 'Crafted in Lagos',
        },
    },
    'midnight-bucket-hat': {
        id: 'midnight-bucket-hat',
        name: 'Midnight',
        tag: 'Bucket Hat',
        category: 'Headwear',
        categoryHash: 'headwear',
        price: 7500,
        image: 'images/61.webp',
        badge: 'Bestseller',
        description:
            'Midnight-black bucket hat with embroidered FakeSmile crest. Cotton twill, structured brim and a signature streetwear silhouette.',
        details: {
            Material: 'Heavy cotton twill',
            Fit: 'One size, adjustable inner band',
            Sizes: 'OS · 56–60cm',
            Care: 'Spot clean only',
            Origin: 'Crafted in Lagos',
        },
    },
    'stone-bucket-hat': {
        id: 'stone-bucket-hat',
        name: 'Stone',
        tag: 'Bucket Hat',
        category: 'Headwear',
        categoryHash: 'headwear',
        price: 7500,
        image: 'images/596.webp',
        description:
            'Stone-cream bucket hat in heavy cotton twill with the FakeSmile crest. Neutral, premium, and pairs with every drop in the catalog.',
        details: {
            Material: 'Heavy cotton twill',
            Fit: 'One size, adjustable inner band',
            Sizes: 'OS · 56–60cm',
            Care: 'Spot clean only',
            Origin: 'Crafted in Lagos',
        },
    },
    'crimson-bucket-hat': {
        id: 'crimson-bucket-hat',
        name: 'Crimson',
        tag: 'Bucket Hat',
        category: 'Headwear',
        categoryHash: 'headwear',
        price: 7500,
        image: 'images/650.webp',
        badge: 'Limited',
        description:
            'Crimson-red bucket hat with the FakeSmile brick crest. Heavy cotton twill, structured brim — the loudest finish on a court fit.',
        details: {
            Material: 'Heavy cotton twill',
            Fit: 'One size, adjustable inner band',
            Sizes: 'OS · 56–60cm',
            Care: 'Spot clean only',
            Origin: 'Crafted in Lagos',
        },
    },
    'olive-globe-cap': {
        id: 'olive-globe-cap',
        name: 'Olive Globe',
        tag: 'Cap',
        category: 'Headwear',
        categoryHash: 'headwear',
        price: 8500,
        image: 'images/651.webp',
        badge: 'New',
        description:
            'Army-olive curved-brim cap carrying the FakeSmile globe patch and the "Smile even if it\'s fake" embroidered tagline. Laser-perforated panels for airflow, black contrast brim trim — a clean field-ready finish.',
        details: {
            Material: 'Performance twill, laser-perforated panels',
            Fit: 'Curved brim, adjustable strap',
            Sizes: 'OS · 56–60cm',
            Care: 'Spot clean only',
            Origin: 'Crafted in Lagos',
        },
    },
    'voltage-globe-cap': {
        id: 'voltage-globe-cap',
        name: 'Voltage Globe',
        tag: 'Cap',
        category: 'Headwear',
        categoryHash: 'headwear',
        price: 8500,
        image: 'images/652.webp',
        badge: 'New',
        description:
            'Midnight-black curved-brim cap with neon-yellow brim trim, the FakeSmile globe patch and the "Smile even if it\'s fake" embroidered script. Laser-perforated panels for breathability — the loudest finish in the rotation.',
        details: {
            Material: 'Performance twill, laser-perforated panels',
            Fit: 'Curved brim, adjustable strap',
            Sizes: 'OS · 56–60cm',
            Care: 'Spot clean only',
            Origin: 'Crafted in Lagos',
        },
    },
};

/** Look up a product by id, returning null if not found. */
function getProduct(id) {
    return id && PRODUCTS[id] ? PRODUCTS[id] : null;
}

/**
 * Returns one random product from each of: Hoodie, Tee, Joggers, Shorts,
 * Headwear (in that order), excluding the given id. Empty buckets are
 * skipped silently so the row never breaks when a category runs out.
 */
function getRelatedProducts(id) {
    const buckets = { hoodie: [], tee: [], joggers: [], shorts: [], headwear: [] };
    Object.values(PRODUCTS).forEach((p) => {
        if (p.id === id) return;
        if (p.tag === 'Hoodie') buckets.hoodie.push(p);
        else if (p.tag === 'Tee') buckets.tee.push(p);
        else if (p.tag === 'Joggers') buckets.joggers.push(p);
        else if (p.tag === 'Shorts') buckets.shorts.push(p);
        else if (p.category === 'Headwear') buckets.headwear.push(p);
    });
    const pick = (arr) => arr.length ? arr[Math.floor(Math.random() * arr.length)] : null;
    return [buckets.hoodie, buckets.tee, buckets.joggers, buckets.shorts, buckets.headwear]
        .map(pick)
        .filter(Boolean);
}
